In [2]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4,5])
type(arr)

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
type(arr_2d)

arr_3d = np.array([[
        [1,2],[3,4]
    ],
    [
        [5,6],[7,8]
    ]
    ])
type(arr_3d)
print(f"shape of tensor is {arr_3d.shape}")
print(f"size of tensor is {arr_3d.size}")


shape of tensor is (2, 2, 2)
size of tensor is 8


In [16]:
print(np.random.rand(4,4))

print(np.zeros((2,3),dtype=int))
print(np.zeros((5,5)))

print(np.ones((3,5)))

print(np.full((3,3),5)) #np.full(shape_of_tensor, value)

print(np.empty((3,3)))


[[0.2811247  0.53591694 0.93154014 0.89398901]
 [0.51487443 0.61385144 0.40473326 0.62396223]
 [0.87291143 0.57847137 0.98579539 0.33522886]
 [0.73444138 0.93225937 0.65543045 0.75628893]]
[[0 0 0]
 [0 0 0]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]


In [23]:
arr =np.arange(1,11,1)
print(arr.reshape(5, 2))
print(arr.flatten()) 

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[ 1  2  3  4  5  6  7  8  9 10]


In [25]:
print(np.linspace(1,10,11))

[ 1.   1.9  2.8  3.7  4.6  5.5  6.4  7.3  8.2  9.1 10. ]


In [ ]:
arr1 = np.random.rand(10)
arr2 = np.random.rand(10)
print(np.intersect1d(arr1, arr2))

print(arr1 + arr)


[]
[0.85153289 0.95045729 1.09980958 0.73201643 0.71790167 0.98280902
 0.05204299 1.0736318  1.65673284 0.9830897 ]


AttributeError: 'list' object has no attribute 'shape'

In [52]:
arr = np.random.rand(100,1000,1000)
np.save("dataset", arr)

In [53]:
np.load("./dataset.npy")

array([[[0.28979036, 0.17882368, 0.52322849, ..., 0.31689364,
         0.15332626, 0.69494362],
        [0.25271501, 0.46017614, 0.01435318, ..., 0.62242254,
         0.69605048, 0.62739964],
        [0.69976749, 0.20313047, 0.1999222 , ..., 0.7125925 ,
         0.9119719 , 0.68342755],
        ...,
        [0.36660803, 0.68080039, 0.3990813 , ..., 0.7188918 ,
         0.40533524, 0.41294401],
        [0.65879001, 0.10271357, 0.05890075, ..., 0.03575047,
         0.86053675, 0.38719055],
        [0.70397893, 0.7877581 , 0.51134386, ..., 0.22879187,
         0.2616409 , 0.85097157]],

       [[0.42987882, 0.53523353, 0.64901158, ..., 0.91507644,
         0.46356296, 0.51426408],
        [0.73870717, 0.99621889, 0.86068342, ..., 0.0028219 ,
         0.54651835, 0.61928632],
        [0.47589937, 0.78384923, 0.43368205, ..., 0.34811944,
         0.86023578, 0.86503576],
        ...,
        [0.62326145, 0.37897289, 0.48865039, ..., 0.23722361,
         0.91157437, 0.12274539],
        [0.0

In [56]:
print(np.mean(np.random.rand(23)))

0.45956145706299095


In [79]:
print(np.mode(np.random.rand(20)))

AttributeError: module 'numpy' has no attribute 'mode'